name: Build and push Docker image on commit to main

on:
    push:
        branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t jacobg431/jacobgomezhansen.net:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push jacobg431/jacobgomezhansen.net:latest

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 2222
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull jacobg431/jacobgomezhansen.net:latest
            docker stop jacobgomezhansen.net || true
            docker rm jacobgomezhansen.net || true
            docker run -d --name jacobgomezhansen.net -p 4173:4173 jacobg431/jacobgomezhansen.net:latest